"{{{ vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
"}}}

"Plugins {{{
Plug 'airblade/vim-gitgutter'
Plug 'vim-scripts/camelcasemotion'

Plug 'christoomey/vim-tmux-navigator'
let g:tmux_navigator_save_on_switch = 3

"Plug 'davidhalter/jedi-vim'
Plug 'vim-scripts/DoxygenToolkit.vim'
Plug 'gmarik/vundle'
Plug 'godlygeek/tabular'
Plug 'gregsexton/gitv'
Plug 'joonty/vdebug'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/vim-plug'
Plug 'kien/ctrlp.vim'
Plug 'Konfekt/FastFold'
Plug 'lervag/vimtex'
Plug 'Lokaltog/vim-easymotion'
Plug 'ludovicchabant/vim-gutentags'
"Plug 'majutsushi/tagbar'
Plug 'vim-scripts/Match-Bracket-for-Objective-C'
Plug 'mattboehm/vim-accordion'
"Plug 'maralla/completor.vim'
Plug 'mbbill/undotree'
Plug 'mileszs/ack.vim'
Plug 'msanders/cocoa.vim'
Plug 'Raimondi/delimitMate'
Plug 'vim-scripts/ReplaceWithRegister'
Plug 'rickhowe/diffchar.vim'
Plug 'rizzatti/dash.vim'
Plug 'rizzatti/funcoo.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
"Plug 'ShowMarks'
Plug 'skywind3000/asyncrun.vim'
Plug 'sukima/xmledit'
	Plug 'vim-scripts/tcd.vim'
Plug 'tmhedberg/SimpylFold'
Plug 'tmux-plugins/vim-tmux'
Plug 'tommcdo/vim-lion'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
"Plug 'tpope/vim-rsi'
"Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-speeddating'
	Plug 'tpope/vim-surround'
Plug 'Valloric/ListToggle'
Plug 'vim-scripts/VHDL-indent-93-syntax'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'vim-scripts/VisIncr'
Plug 'wincent/ferret'
Plug 'wincent/loupe'
Plug 'wincent/scalpel'
Plug 'wincent/terminus'
Plug 'xu-cheng/brew.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
"Plug 'YankRing.vim'
Plug 'vim-scripts/ZoomWin'

Plug 'mattboehm/vim-unstack'
let g:unstack_layout = "portrait"

Plug 'derekwyatt/vim-protodef'
let protodefprotogetter=$VIM.'bundles/protodef/pullproto.pl'
let disable_protodef_sorting=1

"Plug 'ervandew/supertab'
"	let g:SuperTabDefaultCompletionType = "<c-n>"

Plug 'haya14busa/incsearch.vim'
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

Plug 'vimwiki/vimwiki'
let g:vimwiki_list = 	[{'path': '~/vimwiki/certus', 'path_html': '~/mnt/fileserver/IT/Dokumentation/', 'auto_export': 1, 'auto_toc': 1, 'maxhi': 1 },
						\{'path': '~/vimwiki/crazor', 'maxhi': 1 }]

"Python mode
Plug 'python-mode/python-mode', { 'branch': 'develop' }
set completeopt+=noinsert
let g:pymode_rope = 1
let g:pymode_rope_autoimport = 1
let g:pymode_rope_autoimport_import_after_complete = 1

"Plug 'altercation/vim-colors-solarized'
"set termguicolors
""let g:solarized_termtrans=1
"set background=light
""let g:solarized_termcolors=256

"Airline/Promptline/Tmuxline
Plug 'vim-airline/vim-airline'
let g:airline_powerline_fonts = 1
"Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/promptline.vim'
let g:airline#extensions#tabline#enabled = 1
Plug 'edkolev/tmuxline.vim'
let g:airline#extensions#tmuxline#enabled = 1
let g:airline_theme = 'codedark'

"Colorscheme
Plug 'tomasiser/vim-code-dark'

call plug#end()

colorscheme codedark
set cursorline
"}}}

"Grundlegende Konfiguration {{{

"Keine Warntöne
set visualbell t_vb=

"Deutsch =)
set helplang=de

"Verzeichnis für viminfo
set viminfo+=!
set viminfo+=n~/.vim/.viminfo

"Erlaube Verstecken von nicht gespeicherten Buffern
set hidden

"Syntax Highlighting
syntax enable

"Wildmenu (Vervollständigung)
set wildmenu

"Unvollständige Kommandos anzeigen
set showcmd

"History-Größe
set history=100

"Fenster rechts und unten öffnen
set splitright
set splitbelow

"Durchgehender Strich zwischen Splits
set fillchars=vert:┃

"minimale Fenstergröße
set winminheight=0
set winminwidth=0

"Änderungen an .vimrc beim Speichern übernehmen
augroup reload_vimrc
	autocmd!
	autocmd bufwritepost $MYVIMRC nested source $MYVIMRC
augroup END

"Bei :make usw. automatisch speichern
set autowrite

"Zeilennummern
set number
"relative Zeilennummern
set relativenumber
" ^ Die Kombination aus 'nu' und 'rnu' zeigt die absolute Zeilennummer in der
" aktuellen Zeile an

"Cursorposition anzeigen
set ruler

"Zeilenumbruch
set linebreak
				"8 Maskierte Leerzeichen =)
set showbreak=\ \ \ \ \ \ \ \ 
set cpoptions+=n

"list mode schöner machen
set listchars=tab:>-

"Backspace reparieren
set backspace=indent,eol,start

"Wrapping für Cursor
set whichwrap=b,s,<,>,[,]

"Rand für Umbruch
"set colorcolumn=81

"Passende Klammer anzeigen
set showmatch

"Buffer in anderen Tabs wiederverwenden
set switchbuf=usetab

"Letzte Zeile möglichst vollständig anzeigen
set display=lastline

"Zeilen bis zum Bildschirmrand
set scrolloff=3

"Folding
set foldenable
set foldmethod=marker

"Indentation
set shiftwidth=4
set tabstop=4
set smarttab
set autoindent
set smartindent

"Search options
set ignorecase
set smartcase
set incsearch
set hlsearch

"J ein wenig Benehmen beibringen
set nojoinspaces

"Kommentarzeichen beim Join entfernen
set formatoptions+=j

"Immer Statuszeile anzeigen
set laststatus=2

"Macros beschleunigen
set lazyredraw

"System-Zwischenablage verwenden
set clipboard=unnamed

"Persistant Undo
silent !mkdir -p ~/.vim/undo
set undodir=~/.vim/undo
set undofile

"NetRW
let g:netrw_liststyle=3 "Tree style listing

"Vimpager
"let g:vimpager.passthrough=0

"Leader
let mapleader = ","
"}}}

"Autocommands {{{
"Automatisch an die letzte Cursorposition springen
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

"Splits neu aufteilen bei Änderung der Fenstergröße
autocmd VimResized * execute "normal! \<C-w>="

"Highlighting
autocmd BufNewFile,BufReadPost *.ino,*.pde set filetype=cpp

let g:xml_syntax_folding=1
au FileType xml setlocal foldmethod=syntax

"Whitespaces am Ende einer Zeile anzeigen und löschen
autocmd InsertEnter * syn clear EOLWS | syn match EOLWS excludenl /\s\+\%#\@!$/
autocmd InsertLeave * syn clear EOLWS | syn match EOLWS excludenl /\s\+$/
highlight EOLWS ctermbg=red guibg=red

function! <SID>StripTrailingWhitespace()
	" Preparation: save last search, and cursor position.
	let _s=@/
	let l = line(".")
	let c = col(".")
	" Do the business:
	%s/\s\+$//e
	" Clean up: restore previous search history, and cursor position
	let @/=_s
	call cursor(l, c)
endfunction
nnoremap <silent> <Leader><space> :call <SID>StripTrailingWhitespace()<CR>

"Hilfe in Tab öffnen
"augroup HelpInTabs
	"    autocmd!
"    autocmd BufEnter *.txt call HelpInNewTab()
"augroup END

function! HelpInNewTab()
	if &buftype == 'help'
		silent execute "normal \<C-W>T"
	endif
endfunction

" Suchtreffer immer in die Bildschirmmitte
nnoremap n nzz

"}}}

"MacVim {{{
function! Fu()
	set fullscreen
	set lines=200
	set columns=300
endfunction
:command! Fu call Fu()

function! Nofu()
	set nofullscreen
	set lines=25
	set columns=95
endfunction
:command! Nofu call Nofu()
"}}}

"Mappings {{{

"Leader
let mapleader = ","

"Write all
nnoremap <Leader>w :wa<cr>

"fswitch mappings
nnoremap <silent> <Leader>of :FSHere<cr>
nnoremap <silent> <Leader>ol :FSRight<cr>
nnoremap <silent> <Leader>oL :FSSplitRight<cr>
nnoremap <silent> <Leader>oh :FSLeft<cr>
nnoremap <silent> <Leader>oH :FSSplitLeft<cr>
nnoremap <silent> <Leader>ok :FSAbove<cr>
nnoremap <silent> <Leader>oK :FSSplitAbove<cr>
nnoremap <silent> <Leader>oj :FSBelow<cr>
nnoremap <silent> <Leader>oJ :FSSplitBelow<cr>

"LaTeX Umlaute
"function! Texmap()
	"inoremap ö "o
	"inoremap ä "a
	"inoremap ü "u
	"inoremap Ä "A
	"inoremap Ö "O
	"inoremap Ü "U
	"inoremap ß "s
"endfunction

"function! Untexmap()
	"iunmap ö
	"iunmap ä
	"iunmap ü
	"iunmap Ä
	"iunmap Ö
	"iunmap Ü
	"iunmap ß
"endfunction
":command! Tex call Texmap()
":command! Untex call Untexmap()

"Wer braucht schon den Ex-Mode?
noremap Q gq

"Synctex
noremap <Leader>r :w<CR>:silent !/Applications/Skim.app/Contents/SharedSupport/displayline <C-r>=line('.')<CR> %<.pdf %<CR>

"Edit Mappings
cnoremap $h e ~/
cnoremap $d e ~/Desktop/
cnoremap $$ e ./

"Als root schreiben
cnoremap w!! % !sudo tee % > /dev/null

"Bracketed paste mode Unterstützung
"if &term =~ "xterm.*"
"    let &t_ti = &t_ti . "\e[?2004h"
"    let &t_te = "\e[?2004l" . &t_te
"    function! XTermPasteBegin(ret)
"        set pastetoggle=<Esc>[201~
"        set paste
"        return a:ret
"    endfunction
"    noremap <expr> <Esc>[200~ XTermPasteBegin("i")
"    inoremap <expr> <Esc>[200~ XTermPasteBegin("")
"endif

noremap <Up> <C-y>
noremap <Down> <C-e>
noremap <Left> <NOP>
noremap <Right> <NOP>

"Space toggles folds
"Breaks Ctrl+F and PgDwn
"nnoremap <Space> za

"Move lines up and down
noremap <Leader>j ddp
noremap <Leader>k ddkP

"Tabs wechseln
noremap <Leader>, gT
noremap <Leader>. gt

"Manpages
runtime! ftplugin/man.vim
let g:ft_man_open_mode = 'vert'
set keywordprg=:Man

"""Command mode
cnoremap <C-a> <Home>
cnoremap <C-e> <End>

"Insert at begining of last insertion
nnoremap <Leader>i `[i

"Easier visual indentation
vnoremap < <gv 
vnoremap > >gv

"}}}
